@startuml
title Таблица трассировки скалярного произведения векторов
skinparam backgroundColor white
skinparam {
    defaultFontSize 12
    defaultTextAlignment center
}

salt
{
    {^"Векторы:\nx = [1, 2, 1, 2, 1, 2, 1]\ny = [1,-2, 3, 4, 5,-6, 7]"
    |= Вызов |= s |= x[s-1] |= y[s-1] |= Произведение |= Накопленная сумма
    | func(x,y,7) | 7 | 1 | 7 | 7 | 8
    | func(x,y,6) | 6 | 2 | -6 | -12 | -4
    | func(x,y,5) | 5 | 1 | 5 | 5 | 1
    | func(x,y,4) | 4 | 2 | 4 | 8 | 9
    | func(x,y,3) | 3 | 1 | 3 | 3 | 12
    | func(x,y,2) | 2 | 2 | -2 | -4 | 8
    | func(x,y,1) | 1 | 1 | 1 | 1 | 9
    | func(x,y,0) | 0 | - | - | 0 | 0
    }
}

legend right
    Как читать таблицу:
    s - текущий размер
    x[s-1], y[s-1] - текущие элементы
    Произведение - x[s-1] * y[s-1]
    Накопленная сумма - сумма всех
    предыдущих произведений
end legend

@enduml
